### PR TITLE
Update dependencies and use new theme/base

### LINKED ISSUE #35: G0.35 Update dependancies to include new theme/base
### Branch

g0.35-updateDependenciesAndTheme

### Groups

Group 0 - General

### Describe

The new Tripal Cultivate base module has been created and should be a dependancy for this package. Additionally, we have a new TripalCultivate theme which we would like to use in our docker images.

### Design

No design needed.

### PR DESCRIPTION
**Pull request by laceysanderson**
**Issue #35**

## Motivation

Based on the changes made in https://github.com/TripalCultivate/TripalCultivate/pull/8 we need to update all the packages.

## What does this PR do?
*Please describe each things this PR does. For example, a PR may 1) solve a specific bug, 2) create an automated test to ensure it doesn't return.*

1. Updates dependencies (i.e. Drupal version, Tripal Cultivate Base)
2. Dockerfile now uses TripalCultivate base image instead of Tripal core
3. Update all github action versions to remove warning about Node 20
4. Update automated testing grid to include Drupal 10.2 and PHP 8.2
5. Update all workflows to allow them to be manually triggered and to ensure they are run each night on the most recent changes in dependencies.

NOTE: This module is not yet compatible with Drupal 10.2 so the failing tests for that version of Drupal are expected. This will be fixed in Issue https://github.com/TripalCultivate/TripalCultivate-Genetics/issues/37

### Automated Testing
No additional automated testing needed for these changes.

### Manual Testing
*Describe in detail how someone should manually test this functionality.*
*Make sure to include whether they need to build a docker from scratch, create any records, etc.*

1. Check that the automated testing passes. This confirms changes to dependencies, workflows and the Dockerfile did not cause any issues.
2. Build a docker image locally and run a container just to take a look at things.
    - everything is installed and chado is in a schema named `testschema`
    - the content types you expect are available (note: additionally the genetic and genomic will now be available).
    - confirm that the site is now themed green as expected for Tripal Cultivate.

### CODE REVIEW

**Review by carolyncaron — DISMISSED** [review]
1. Automated tests are only failing for Drupal 10.2, as noted would happen.
2. I was unable to access the site after building the docker image and running the container. Here are the steps I took:

-  Cloned this repository
- `docker build --tag=trpcultivate:latest .`
- `docker run --publish=80:80 --name=trpcultivate -tid --volume=`pwd`:/var/www/drupal/web/modules/contrib/TripalCultivate-Genetics trpcultivate:latest`
- `docker exec trpcultivate service postgresql restart`
- There were no errors on the command line. When I go to localhost in both Chrome and Firefox I get:
Screen Shot 2024-04-09 at 3 21 09 PM


- And here are the logs for my container:
> 2024-04-09 14:59:40 2024-04-09 20:59:40,699 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-04-09 14:59:40 2024-04-09 20:59:40,706 INFO supervisord started with pid 9
2024-04-09 14:59:41 2024-04-09 20:59:41,721 INFO spawned: 'apachectl' with pid 12
2024-04-09 14:59:42 [Tue Apr 09 20:59:42.060549 2024] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.56 (Debian) PHP/8.3.4 configured -- resuming normal operations
2024-04-09 14:59:42 [Tue Apr 09 20:59:42.062275 2024] [core:notice] [pid 18] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
2024-04-09 14:59:43 2024-04-09 20:59:43,066 INFO success: apachectl entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-09 15:01:16 [Tue Apr 09 21:01:16.716870 2024] [php:error] [pid 23] [client 192.168.65.1:33775] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Database/ChadoSchema.php on line 80
2024-04-09 15:01:16 192.168.65.1 - - [09/Apr/2024:21:00:08 +0000] "GET / HTTP/1.1" 200 444 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
2024-04-09 15:02:38 [Tue Apr 09 21:02:38.116272 2024] [php:error] [pid 21] [client 192.168.65.1:33840] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/drupal/web/core/lib/Drupal/Core/Database/Query/Select.php on line 553
2024-04-09 15:02:38 192.168.65.1 - - [09/Apr/2024:21:01:26 +0000] "GET / HTTP/1.1" 200 435 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
2024-04-09 15:03:02 [Tue Apr 09 21:03:02.963071 2024] [php:error] [pid 25] [client 192.168.65.1:33857] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/drupal/web/core/modules/pgsql/src/Driver/Database/pgsql/Connection.php on line 253
2024-04-09 15:03:02 192.168.65.1 - - [09/Apr/2024:21:01:51 +0000] "GET / HTTP/1.1" 200 440 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"

**Comment by laceysanderson** [comment]
Thanks for your review @carolyncaron, I'm not able to replicate this at home 🙈 I can confirm that the logs of my docker that works matches yours until mention of the max execution time being reached (15:01:16 [Tue Apr 09 21:01:16.716870 2024]). Maybe this is related to resources? I have 4 CPU, 3GB memory and 1GB swap given to my docker so it's pretty conservative. What are the resources you are running docker with?

**Comment by carolyncaron** [comment]
My docker has access to 8 CPU, 5GB RAM and 1GB swap 😬

**Review by reynoldtan — APPROVED** [review]
👍 I did not get a max execution time out on my windows machine

**Comment by carolyncaron** [comment]
I confirmed that the timeout issue also occurs for me for the same PR in https://github.com/TripalCultivate/TripalCultivate-Germplasm/pull/15 , but I am on a different computer from when I did the previous review. Since this works for Reynold we're going to assume this issue is not due to this PR but is isolated to my laptop and try to debug the problem from there.

**Comment by laceysanderson** [comment]
Thanks everyone!

**Pull request merged**
